from __future__ import annotations

import ast
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
MAIN_WINDOW_PATH = REPO_ROOT / "ui" / "main_window.py"

ALLOWED_UI_DIRECT_IMPORTS = {
    "ui/dialogs/advanced_figure_dialog.py": {("ui.widgets.focus_commit", "install_click_away_focus_commit")},
    "ui/dialogs/ai_tool_dialog.py": {
        ("core.global_assets", "global_assets"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/dialogs/calibration_dialog.py": {
        ("ui.theme", "border_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "surface_color"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/dialogs/coord_type_dialog.py": {
        ("ui.theme", "border_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "surface_color"),
    },
    "ui/dialogs/export_flow.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/dialogs/fluent_dialogs.py": {("ui.widgets.focus_commit", "install_click_away_focus_commit")},
    "ui/dialogs/import_dialog.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
        ("models.schemas", "DataSeries"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/dialogs/plot_extension_instance_dialog.py": {
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_entry_display_info"),
        ("core.extension_api", "extension_entry_parameter_help_text"),
        ("ui.widgets.extension_options_form", "ExtensionOptionsForm"),
    },
    "ui/dialogs/polar_calibration_dialog.py": {
        ("ui.theme", "border_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "surface_color"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/dialogs/project_tree_manage_dialog.py": {
        ("ui.theme", "WORKBENCH_BUTTON_MIN_WIDTH"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.widgets.project_tree", "ProjectTreeWidget"),
    },
    "ui/dialogs/report_template_dialog.py": {
        ("core.analysis_engine", "list_report_template_placeholders"),
        ("core.analysis_engine", "render_report"),
        ("core.global_assets", "global_assets"),
        ("core.report_templates", "DEFAULT_REPORT_TEMPLATE"),
        ("models.schemas", "ReportTemplate"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "border_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "surface_color"),
        ("ui.theme", "text_color"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/main_window.py": {
        ("", "core.project_manager"),
        ("app.context", "AppContext"),
        ("app.messages", "AppCommand"),
        ("app.messages", "AppCommandType"),
        ("app.messages", "TreeCommand"),
        ("app.tree_action_dispatcher", "ProjectTreeActionDispatcher"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "reload_extensions"),
        ("core.extension_registry", "extension_registry"),
        ("core.extension_settings", "delete_external_extension_file"),
        ("core.global_assets", "global_assets"),
        ("core.i18n", "_"),
        ("core.i18n", "reload_translations"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("core.shortcut_manager", "shortcut_manager"),
        ("core.ui_preferences", "get_auto_save_enabled"),
        ("core.ui_preferences", "get_auto_save_interval_seconds"),
        ("core.ui_preferences", "is_page_tree_focus_mode_enabled"),
        ("core.ui_preferences", "reset_all_onboarding_progress"),
    },
    "ui/pages/analysis_page.py": {
        ("", "core.project_manager"),
        ("app.workspaces.analysis_workspace", "AnalysisWorkspaceController"),
        ("app.workspaces.analysis_workspace", "AnalysisWorkspaceState"),
        ("core.analysis_engine", "list_report_template_placeholders"),
        ("core.analysis_engine", "render_report"),
        ("core.analysis_engine", "run_analysis"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_lines_number"),
        ("core.extension_api", "extension_lines_picker_visible"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "normalize_extension_lines_list"),
        ("core.extension_api", "reload_configured_extensions"),
        ("core.extension_api", "validate_extension_lines_list"),
        ("core.global_assets", "global_assets"),
        ("core.report_templates", "DEFAULT_REPORT_TEMPLATE"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("core.task_runner", "TaskManager"),
        ("models.schemas", "AnalysisResult"),
        ("models.schemas", "DataFile"),
        ("models.schemas", "DataSeries"),
        ("processing.extension_tools", "line_from_xy"),
        ("processing.extension_tools", "line_xy"),
        ("processing.extension_tools", "normalize_line"),
        ("ui.dialogs.export_flow", "DataCreateTargetOption"),
        ("ui.dialogs.export_flow", "choose_analysis_result_save_plan"),
        ("ui.dialogs.export_flow", "choose_data_export_plan"),
        ("ui.dialogs.fluent_dialogs", "SelectionDialog"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.notifications", "show_error"),
        ("ui.notifications", "show_warning"),
        ("ui.page_view_state", "AnalysisPageViewState"),
        ("ui.pages.save_export_coordinator", "SaveExportCoordinator"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "WORKBENCH_BUTTON_MIN_WIDTH"),
        ("ui.theme", "WORKBENCH_TOOL_PANEL_WIDTH"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.theme", "make_hint_label"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "placeholder_color"),
        ("ui.widgets.extension_options_form", "ExtensionOptionsForm"),
        ("ui.widgets.extension_panel", "ExtensionConfigPanel"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
        ("ui.widgets.matplotlib_preview", "attach_preview_gesture_buttons"),
        ("ui.widgets.matplotlib_preview", "build_preview_toolbar"),
        ("ui.widgets.matplotlib_preview", "create_navigation_toolbar"),
        ("ui.widgets.matplotlib_preview", "sync_preview_nav_toggle_states"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_box_zoom_mode"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_pan_mode"),
        ("ui.widgets.matplotlib_preview", "zoom_figure_axes"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
        ("ui.widgets.right_panel_container", "RightPanelContainer"),
    },
    "ui/pages/analysis_page_support.py": {("ui.matplotlib_fonts", "bootstrap_matplotlib_qtagg")},
    "ui/pages/chart_page.py": {
        ("", "core.project_manager"),
        ("app.workspaces.chart_workspace", "ChartWorkspaceController"),
        ("app.workspaces.chart_workspace", "ChartWorkspaceState"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "PlotExtensionContext"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "compare_extension_versions"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "reload_configured_extensions"),
        ("core.extension_runtime", "invoke_plot_extension_handler"),
        ("core.global_assets", "ExtensionConfigPreset"),
        ("core.global_assets", "global_assets"),
        ("core.global_assets", "make_plot_style_asset_key"),
        ("core.global_assets", "parse_plot_style_asset_key"),
        ("core.rendering", "RenderDecimationPolicy"),
        ("core.rendering", "decimate_xy_for_rendering"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("core.task_runner", "TaskManager"),
        ("models.schemas", "AxisConfig"),
        ("models.schemas", "CurveStyle"),
        ("models.schemas", "CurveStyleTemplate"),
        ("models.schemas", "FigureConfig"),
        ("models.schemas", "FigureState"),
        ("models.schemas", "PicturePlotExtensionSnapshot"),
        ("models.schemas", "PicturePlotExtraVersion"),
        ("models.schemas", "PicturePlotSeriesSnapshot"),
        ("models.schemas", "PicturePlotSnapshot"),
        ("models.schemas", "SavedPlotPipeline"),
        ("processing.downsample", "downsample_lttb"),
        ("processing.downsample", "should_downsample"),
        ("ui.dialogs.export_flow", "choose_picture_export_plan"),
        ("ui.dialogs.fluent_dialogs", "SelectionDialog"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.dialogs.plot_extension_instance_dialog", "PlotExtensionInstanceEditDialog"),
        ("ui.matplotlib_fonts", "list_matplotlib_font_families"),
        ("ui.page_view_state", "ChartPageViewState"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "WORKBENCH_BUTTON_MIN_WIDTH"),
        ("ui.theme", "WORKBENCH_TOOL_PANEL_WIDTH"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "make_hint_label"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "preview_canvas_background_color"),
        ("ui.theme", "preview_canvas_foreground_color"),
        ("ui.theme", "preview_canvas_grid_color"),
        ("ui.theme", "secondary_text_style_sheet"),
        ("ui.widgets.extension_options_form", "ExtensionOptionsForm"),
        ("ui.widgets.extension_options_form", "_LineSelectionDialog"),
        ("ui.widgets.extension_panel", "ExtensionConfigPanel"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
        ("ui.widgets.matplotlib_preview", "attach_preview_gesture_buttons"),
        ("ui.widgets.matplotlib_preview", "build_preview_toolbar"),
        ("ui.widgets.matplotlib_preview", "create_navigation_toolbar"),
        ("ui.widgets.matplotlib_preview", "preview_navigation_mode"),
        ("ui.widgets.matplotlib_preview", "sync_preview_nav_toggle_states"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_box_zoom_mode"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_pan_mode"),
        ("ui.widgets.matplotlib_preview", "zoom_figure_axes"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
        ("ui.widgets.right_panel_container", "RightPanelContainer"),
    },
    "ui/pages/chart_page_support.py": {
        ("core.extension_api", "PlotExtension"),
        ("core.extension_api", "PlotExtensionContext"),
        ("models.schemas", "FigureState"),
        ("ui.matplotlib_fonts", "bootstrap_matplotlib_qtagg"),
    },
    "ui/pages/data_page.py": {
        ("", "core.project_manager"),
        ("app.workspaces.data_workspace", "DataWorkspaceController"),
        ("app.workspaces.data_workspace", "DataWorkspaceState"),
        ("core.app_context", "get_app_context"),
        ("core.exporter", "Exporter"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_entry_display_info"),
        ("core.extension_api", "extension_entry_parameter_help_text"),
        ("core.extension_api", "extension_lines_support_text"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "normalize_extension_lines_number"),
        ("core.extension_api", "validate_extension_lines_list"),
        ("core.extension_registry", "extension_registry"),
        ("core.global_assets", "global_assets"),
        ("core.global_assets", "parse_plot_style_asset_key"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("core.ui_preferences", "get_data_page_source_favorites"),
        ("core.ui_preferences", "set_data_page_source_favorites"),
        ("models.schemas", "Curve"),
        ("models.schemas", "CurveStyleTemplate"),
        ("models.schemas", "DataFile"),
        ("models.schemas", "DataSeries"),
        ("models.schemas", "Dataset"),
        ("models.schemas", "FigureConfig"),
        ("models.schemas", "ReportTemplate"),
        ("models.schemas", "SavedPipeline"),
        ("models.schemas", "SavedPlotPipeline"),
        ("ui.dialogs.export_flow", "choose_curve_file_export_plan"),
        ("ui.dialogs.export_flow", "curve_export_file_filter"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.dialogs.import_dialog", "ImportDialog"),
        ("ui.dialogs.import_dialog", "SUPPORTED_IMPORT_SUFFIXES"),
        ("ui.dialogs.import_dialog", "analyze_file_preview"),
        ("ui.dialogs.import_dialog", "get_excel_sheet_names"),
        ("ui.dialogs.import_dialog", "read_text_preview_page"),
        ("ui.dialogs.node_remark_dialog", "NodeRemarkDialog"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "WORKBENCH_BUTTON_MIN_WIDTH"),
        ("ui.theme", "WORKBENCH_TOOL_PANEL_WIDTH"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.theme", "border_color"),
        ("ui.theme", "card_background_color"),
        ("ui.theme", "hover_color"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_inline_label"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "preview_canvas_background_color"),
        ("ui.theme", "preview_canvas_foreground_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "surface_color"),
        ("ui.theme", "text_color"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
        ("ui.widgets.matplotlib_preview", "attach_preview_gesture_buttons"),
        ("ui.widgets.matplotlib_preview", "build_preview_toolbar"),
        ("ui.widgets.matplotlib_preview", "create_navigation_toolbar"),
        ("ui.widgets.matplotlib_preview", "preview_navigation_mode"),
        ("ui.widgets.matplotlib_preview", "sync_preview_nav_toggle_states"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_box_zoom_mode"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_pan_mode"),
        ("ui.widgets.matplotlib_preview", "zoom_figure_axes"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
        ("ui.widgets.project_tree_support", "folder_display_name"),
        ("ui.widgets.project_tree_support", "is_protected_folder"),
    },
    "ui/pages/data_page_state_bridge.py": {("ui.page_view_state", "DataPageViewState")},
    "ui/pages/data_page_support.py": {("ui.matplotlib_fonts", "bootstrap_matplotlib_qtagg")},
    "ui/pages/digitize_page.py": {
        ("", "core.project_manager"),
        ("app.workspaces.digitize_workspace", "DigitizeWorkspaceController"),
        ("app.workspaces.digitize_workspace", "DigitizeWorkspaceState"),
        ("core.app_context", "get_app_context"),
        ("core.exporter", "Exporter"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "reload_configured_extensions"),
        ("core.extension_runtime", "invoke_digitize_extension_handler"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("models.schemas", "CalibrationData"),
        ("models.schemas", "DataFile"),
        ("models.schemas", "DataSeries"),
        ("processing.extension_tools", "line_xy"),
        ("ui.dialogs", "CalibrationDialog"),
        ("ui.dialogs", "CoordTypeDialog"),
        ("ui.dialogs", "PolarCalibrationDialog"),
        ("ui.dialogs.export_flow", "DataCreateTargetOption"),
        ("ui.dialogs.export_flow", "choose_curve_file_export_plan"),
        ("ui.dialogs.export_flow", "choose_data_export_plan"),
        ("ui.dialogs.export_flow", "curve_export_file_filter"),
        ("ui.dialogs.project_close_dialog", "ProjectCloseDecision"),
        ("ui.dialogs.project_close_dialog", "confirm_unsaved_project_close"),
        ("ui.page_view_state", "DigitizePageViewState"),
        ("ui.pages.save_export_coordinator", "SaveExportCoordinator"),
        ("ui.theme", "WORKBENCH_TOOL_PANEL_WIDTH"),
        ("ui.theme", "border_color"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "make_vsep"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "text_color"),
        ("ui.widgets", "ImageViewer"),
        ("ui.widgets.extension_panel", "ExtensionConfigPanel"),
        ("ui.widgets.image_viewer", "CurveOverlayItem"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
        ("ui.widgets.right_panel_container", "RightPanelContainer"),
    },
    "ui/pages/home_page.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "get_extension_load_status"),
        ("core.i18n", "_"),
        ("core.recent_projects", "load_recent"),
        ("core.recent_projects", "remove_recent"),
        ("core.ui_preferences", "is_home_onboarding_completed"),
        ("core.ui_preferences", "set_home_onboarding_completed"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "border_color"),
        ("ui.theme", "card_background_color"),
        ("ui.theme", "flat_status_button_style"),
        ("ui.theme", "hover_color"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "make_empty_state_label"),
        ("ui.theme", "make_hint_label"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "notification_parent"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "secondary_color"),
        ("ui.theme", "text_color"),
        ("ui.theme", "warning_color"),
        ("ui.widgets.extension_panel", "show_extension_load_report_dialog"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
    },
    "ui/pages/process_page.py": {
        ("", "core.project_manager"),
        ("app.workspaces.process_workspace", "ProcessWorkspaceController"),
        ("app.workspaces.process_workspace", "ProcessWorkspaceState"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "ensure_configured_extensions_loaded"),
        ("core.extension_api", "extension_lines_number"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_api", "normalize_extension_lines_list"),
        ("core.extension_api", "reload_configured_extensions"),
        ("core.global_assets", "global_assets"),
        ("core.shortcut_manager", "ShortcutBindingSet"),
        ("core.task_runner", "TaskManager"),
        ("models.schemas", "DataFile"),
        ("models.schemas", "DataSeries"),
        ("models.schemas", "SavedPipeline"),
        ("processing.async_runner", "AsyncPipelineRunner"),
        ("processing.data_engine", "apply_pipeline_to_lines"),
        ("processing.downsample", "downsample_lttb"),
        ("processing.downsample", "should_downsample"),
        ("processing.pipeline_extension", "build_pipeline_extension_definition"),
        ("ui.dialogs.export_flow", "choose_data_export_batch_plan"),
        ("ui.dialogs.export_flow", "choose_data_export_plan"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.matplotlib_fonts", "bootstrap_matplotlib_qtagg"),
        ("ui.page_view_state", "ProcessPageViewState"),
        ("ui.pages.save_export_coordinator", "SaveExportCoordinator"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "WORKBENCH_BUTTON_MIN_WIDTH"),
        ("ui.theme", "WORKBENCH_TOOL_PANEL_WIDTH"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "preview_canvas_background_color"),
        ("ui.theme", "preview_canvas_foreground_color"),
        ("ui.theme", "preview_canvas_grid_color"),
        ("ui.theme", "secondary_color"),
        ("ui.widgets.extension_options_form", "ExtensionOptionsForm"),
        ("ui.widgets.extension_options_form", "_LineSelectionDialog"),
        ("ui.widgets.extension_panel", "ExtensionConfigPanel"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
        ("ui.widgets.matplotlib_preview", "attach_preview_gesture_buttons"),
        ("ui.widgets.matplotlib_preview", "build_preview_toolbar"),
        ("ui.widgets.matplotlib_preview", "create_navigation_toolbar"),
        ("ui.widgets.matplotlib_preview", "preview_navigation_mode"),
        ("ui.widgets.matplotlib_preview", "sync_preview_nav_toggle_states"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_box_zoom_mode"),
        ("ui.widgets.matplotlib_preview", "toggle_preview_pan_mode"),
        ("ui.widgets.matplotlib_preview", "zoom_figure_axes"),
        ("ui.widgets.onboarding", "OnboardingStep"),
        ("ui.widgets.onboarding", "PageOnboardingController"),
        ("ui.widgets.right_panel_container", "RightPanelContainer"),
    },
    "ui/pages/save_export_coordinator.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
    },
    "ui/pages/settings_page.py": {
        ("core.ai.providers", "get_provider_preset"),
        ("core.ai.providers", "list_builtin_models"),
        ("core.ai.providers", "list_provider_keys"),
        ("core.ai_client", "AIClient"),
        ("core.ai_client", "AIConfig"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "get_extension_load_status"),
        ("core.extension_api", "list_builtin_extension_specs"),
        ("core.extension_api", "list_external_extension_specs"),
        ("core.extension_api", "reload_configured_extensions"),
        ("core.extension_settings", "add_external_extension_file"),
        ("core.extension_settings", "delete_external_extension_file"),
        ("core.extension_settings", "get_builtin_extension_settings"),
        ("core.extension_settings", "get_extension_number_decimals"),
        ("core.extension_settings", "get_external_extension_sandbox_enabled"),
        ("core.extension_settings", "get_external_extension_settings"),
        ("core.extension_settings", "get_external_extensions_directories"),
        ("core.extension_settings", "resolve_external_extension_path"),
        ("core.extension_settings", "set_builtin_extension_settings"),
        ("core.extension_settings", "set_extension_number_decimals"),
        ("core.extension_settings", "set_external_extension_sandbox_enabled"),
        ("core.extension_settings", "set_external_extension_settings"),
        ("core.extension_settings", "set_external_extensions_directories"),
        ("core.global_assets", "global_assets"),
        ("core.i18n", "_"),
        ("core.i18n", "reload_translations"),
        ("core.shortcut_manager", "shortcut_manager"),
        ("core.ui_preferences", "TreeNameDisplayMode"),
        ("core.ui_preferences", "get_auto_save_enabled"),
        ("core.ui_preferences", "get_auto_save_interval_seconds"),
        ("core.ui_preferences", "get_tree_name_display_mode"),
        ("core.ui_preferences", "get_ui_language"),
        ("core.ui_preferences", "is_page_tree_focus_mode_enabled"),
        ("core.ui_preferences", "set_auto_save_enabled"),
        ("core.ui_preferences", "set_auto_save_interval_seconds"),
        ("core.ui_preferences", "set_interface_scale"),
        ("core.ui_preferences", "set_page_tree_focus_mode_enabled"),
        ("core.ui_preferences", "set_tree_name_display_mode"),
        ("core.ui_preferences", "set_ui_font_family"),
        ("core.ui_preferences", "set_ui_language"),
        ("models.schemas", "ReportTemplate"),
        ("ui.dialogs.ai_tool_dialog", "AIToolDialog"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.dialogs.report_template_dialog", "ReportTemplateDialog"),
        ("ui.page_view_state", "SettingsPageViewState"),
        ("ui.pages.settings_page_support", "ExtensionManageDialog"),
        ("ui.pages.settings_page_support", "MutableFolderListSettingCard"),
        ("ui.pages.settings_page_support", "build_ai_tab"),
        ("ui.pages.settings_page_support", "build_extensions_tab"),
        ("ui.pages.settings_page_support", "build_general_tab"),
        ("ui.pages.settings_page_support", "build_shortcuts_tab"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "apply_application_font_preference"),
        ("ui.theme", "apply_platform_visual_overrides"),
        ("ui.theme", "body_text_style_sheet"),
        ("ui.theme", "border_color"),
        ("ui.theme", "card_background_color"),
        ("ui.theme", "card_title_style_sheet"),
        ("ui.theme", "error_text_style_sheet"),
        ("ui.theme", "flat_status_button_style"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "notification_parent"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "placeholder_text_style_sheet"),
        ("ui.theme", "secondary_text_style_sheet"),
        ("ui.theme", "text_color"),
        ("ui.theme", "warning_color"),
        ("ui.widgets.extension_panel", "show_extension_load_report_dialog"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
        ("ui.widgets.navigation_stack", "PivotStackWidget"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
    },
    "ui/pages/settings_page_support.py": {
        ("core.ai.providers", "get_provider_preset"),
        ("core.extension_settings", "default_external_extensions_directory"),
        ("core.extension_settings", "get_builtin_extension_settings"),
        ("core.extension_settings", "get_external_extension_settings"),
        ("core.extension_settings", "set_builtin_extension_settings"),
        ("core.extension_settings", "set_external_extension_settings"),
        ("core.i18n", "_"),
        ("core.shortcut_manager", "shortcut_manager"),
        ("core.ui_preferences", "get_auto_save_enabled"),
        ("core.ui_preferences", "get_auto_save_interval_seconds"),
        ("core.ui_preferences", "get_interface_scale"),
        ("core.ui_preferences", "get_tree_name_display_mode"),
        ("core.ui_preferences", "get_ui_font_family"),
        ("core.ui_preferences", "get_ui_language"),
        ("core.ui_preferences", "is_page_tree_focus_mode_enabled"),
        ("ui.theme", "body_text_style_sheet"),
        ("ui.theme", "card_title_style_sheet"),
        ("ui.theme", "effective_ui_font_family"),
        ("ui.theme", "error_text_style_sheet"),
        ("ui.theme", "list_installed_ui_font_families"),
        ("ui.theme", "placeholder_text_style_sheet"),
        ("ui.theme", "secondary_text_style_sheet"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
    },
    "ui/widgets/ai_assistant_panel.py": {
        ("core.ai.context", "AIAssistantContext"),
        ("core.ai.context_collector", "collect_context"),
        ("core.ai.context_resolver", "ContextBundle"),
        ("core.ai.context_resolver", "ContextResolver"),
        ("core.ai.extension_writer", "parse_extension_code"),
        ("core.ai.extension_writer", "save_extension"),
        ("core.ai_client", "AIClient"),
        ("core.extension_api", "reload_configured_extensions"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "card_background_color"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "secondary_color"),
        ("ui.widgets.ai_command_handler", "detect_command"),
        ("ui.widgets.ai_command_handler", "execute_command"),
        ("ui.widgets.ai_command_handler", "get_command_list"),
        ("ui.widgets.ai_context_provider", "AIContextProvider"),
    },
    "ui/widgets/ai_context_provider.py": {
        ("core.global_assets", "global_assets"),
        ("core.project_manager", "project_manager"),
    },
    "ui/widgets/extension_options_form.py": {
        ("core.extension_api", "extension_lines_picker_visible"),
        ("core.extension_api", "extension_lines_support_text"),
        ("core.extension_api", "normalize_extension_lines_list"),
        ("core.extension_api", "normalize_extension_lines_number"),
        ("core.extension_settings", "get_extension_number_decimals"),
        ("core.global_assets", "global_assets"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "WORKBENCH_INLINE_LABEL_WIDTH"),
        ("ui.theme", "apply_button_metrics"),
        ("ui.theme", "border_color"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "make_hint_label"),
        ("ui.theme", "make_inline_label"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "secondary_color"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/widgets/extension_panel.py": {
        ("core.extension_api", "compare_extension_versions"),
        ("core.extension_api", "extension_entry_display_info"),
        ("core.extension_api", "extension_entry_parameter_help_text"),
        ("core.extension_api", "format_extension_load_report"),
        ("core.extension_api", "get_extension_load_status"),
        ("core.extension_api", "normalize_extension_version"),
        ("core.global_assets", "global_assets"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.theme", "WORKBENCH_BUTTON_HEIGHT"),
        ("ui.theme", "accent_color"),
        ("ui.theme", "card_title_style_sheet"),
        ("ui.theme", "flat_status_button_style"),
        ("ui.theme", "install_fluent_tooltip"),
        ("ui.theme", "make_hsep"),
        ("ui.theme", "make_section_label"),
        ("ui.theme", "notification_parent"),
        ("ui.theme", "placeholder_color"),
        ("ui.theme", "placeholder_text_style_sheet"),
        ("ui.theme", "secondary_text_style_sheet"),
        ("ui.theme", "warning_color"),
        ("ui.widgets.extension_options_form", "ExtensionOptionsForm"),
        ("ui.widgets.focus_commit", "install_click_away_focus_commit"),
    },
    "ui/widgets/image_viewer.py": {("digitize.image_io", "load_pixmap_unicode")},
    "ui/widgets/matplotlib_preview.py": {("ui.theme", "install_fluent_tooltip")},
    "ui/widgets/onboarding.py": {
        ("core.ui_preferences", "is_page_onboarding_completed"),
        ("core.ui_preferences", "set_page_onboarding_completed"),
    },
    "ui/widgets/project_tree.py": {
        ("", "core.project_manager"),
        ("app.project_tree_command_service", "ProjectTreeCommandService"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_registry"),
        ("core.extension_definition", "compare_extension_versions"),
        ("core.extension_settings", "create_external_extension_file"),
        ("core.global_assets", "ExtensionConfigPreset"),
        ("core.global_assets", "global_assets"),
        ("core.global_assets", "make_plot_style_asset_key"),
        ("core.global_assets", "parse_plot_style_asset_key"),
        ("core.ui_preferences", "get_tree_name_display_mode"),
        ("models.schemas", "CurveStyleTemplate"),
        ("models.schemas", "FigureConfig"),
        ("models.schemas", "ReportTemplate"),
        ("models.schemas", "SavedPipeline"),
        ("models.schemas", "SavedPlotPipeline"),
        ("ui.dialogs.fluent_dialogs", "SelectionDialog"),
        ("ui.dialogs.fluent_dialogs", "TextInputDialog"),
        ("ui.dialogs.import_dialog", "ImportDialog"),
        ("ui.dialogs.import_dialog", "SUPPORTED_IMPORT_SUFFIXES"),
        ("ui.dialogs.project_close_dialog", "ProjectCloseDecision"),
        ("ui.dialogs.project_close_dialog", "confirm_unsaved_project_close"),
        ("ui.widgets.import_conflict_dialog", "ImportConflictDialog"),
        ("ui.widgets.project_tree_builder", "ProjectTreeBuilder"),
        ("ui.widgets.project_tree_model", "ProjectTreeItem"),
        ("ui.widgets.project_tree_page_dispatcher", "ProjectTreePageDispatcher"),
        ("ui.widgets.project_tree_view", "ProjectTreeView"),
    },
    "ui/widgets/project_tree_drag_drop.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
    },
    "ui/widgets/project_tree_menu_commands.py": {
        ("", "core.project_manager"),
        ("core.app_context", "get_app_context"),
        ("core.extension_api", "build_extension_entry"),
        ("core.extension_api", "extension_registry"),
        ("core.global_assets", "global_assets"),
    },
    "ui/widgets/project_tree_support.py": {("core.i18n", "_")},
    "ui/widgets/right_panel_container.py": {
        ("ui.widgets.ai_assistant_panel", "AIAssistantPanel"),
        ("ui.widgets.extension_panel", "ExtensionConfigPanel"),
        ("ui.widgets.navigation_stack", "SegmentedStackWidget"),
    },
}



ALLOWED_CORE_EXTENSION_IMPORTS = {}
ALLOWED_MAIN_WINDOW_PRIVATE_PAGE_ACCESSES = {
    "chart_page._sync_canvas_display_geometry",
    "chart_page._applied_plot_style_ref",
    "chart_page._refresh_template_combo",
    "chart_page._refresh_curve_style_template_combo",
    "chart_page._refresh_chart_list",
    "chart_page._refresh_style_extension_panel",
}


def _parse_python(path: Path) -> ast.AST:
    return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))


def _iter_python_files(relative_root: str) -> list[Path]:
    root = REPO_ROOT / relative_root
    return sorted(path for path in root.rglob("*.py") if path.is_file())


class _ImportVisitor(ast.NodeVisitor):
    def __init__(self) -> None:
        self.direct_imports: set[tuple[str, str]] = set()
        self.core_extension_imports: set[str] = set()

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        module = node.module or ""
        if module in {"core.project_manager", "core.global_assets", "core.extension_api"}:
            for alias in node.names:
                if alias.name in {"project_manager", "global_assets", "extension_registry"}:
                    self.direct_imports.add((module, alias.name))
        if module.startswith("extensions."):
            self.core_extension_imports.add(module)
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            name = alias.name
            if name.startswith("extensions."):
                self.core_extension_imports.add(name)
        self.generic_visit(node)


class _MainWindowVisitor(ast.NodeVisitor):
    PAGE_ATTRS = {
        "home_page",
        "data_page",
        "chart_page",
        "process_page",
        "analysis_page",
        "digitize_page",
        "settings_page",
    }

    def __init__(self) -> None:
        self.private_page_accesses: set[str] = set()

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if not node.attr.startswith("_"):
            self.generic_visit(node)
            return
        owner = node.value
        if (
            isinstance(owner, ast.Attribute)
            and owner.attr in self.PAGE_ATTRS
            and isinstance(owner.value, ast.Name)
            and owner.value.id == "self"
        ):
            self.private_page_accesses.add(f"{owner.attr}.{node.attr}")
        self.generic_visit(node)


class TestArchitectureGuardrails(unittest.TestCase):
    def test_ui_direct_runtime_imports_are_frozen(self) -> None:
        actual: dict[str, set[tuple[str, str]]] = {}
        for path in _iter_python_files("ui"):
            visitor = _ImportVisitor()
            visitor.visit(_parse_python(path))
            if visitor.direct_imports:
                actual[path.relative_to(REPO_ROOT).as_posix()] = visitor.direct_imports
        self.assertEqual(ALLOWED_UI_DIRECT_IMPORTS, actual)

    def test_core_extensions_imports_are_frozen(self) -> None:
        actual: dict[str, set[str]] = {}
        for path in _iter_python_files("core"):
            visitor = _ImportVisitor()
            visitor.visit(_parse_python(path))
            if visitor.core_extension_imports:
                actual[path.relative_to(REPO_ROOT).as_posix()] = visitor.core_extension_imports
        self.assertEqual(ALLOWED_CORE_EXTENSION_IMPORTS, actual)

    def test_main_window_private_page_accesses_are_frozen(self) -> None:
        visitor = _MainWindowVisitor()
        visitor.visit(_parse_python(MAIN_WINDOW_PATH))
        self.assertEqual(ALLOWED_MAIN_WINDOW_PRIVATE_PAGE_ACCESSES, visitor.private_page_accesses)
